spring.application.name=springboot-demo
spring.main.allow-bean-definition-overriding=true

# Nacos \u914D\u7F6E\u670D\u52A1\u5668\u5730\u5740
#spring.cloud.nacos.config.server-addr=47.116.193.3:8848
spring.cloud.nacos.config.server-addr=localhost:8848
# \u5BFC\u5165 Nacos \u914D\u7F6E
spring.config.import[0]=nacos:springboot-demo.properties?group=SPRING_BOOT_DEMO_GROUP
spring.config.import[1]=nacos:db-mysql.properties?group=SPRING_BOOT_DEMO_GROUP