spring.application.name=springboot-demo
spring.main.allow-bean-definition-overriding=true

# Mysql Configuration
spring.datasource.url: jdbc:mysql://47.116.193.3:3306/demo?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
spring.datasource.username: root
spring.datasource.password: shitouv5
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver

# MyBatis Configuration
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-aliases-package=com.example.springbootdemo.dao
# \u5F00\u542F\u9A7C\u5CF0\u547D\u540D\u8F6C\u6362
mybatis.configuration.map-underscore-to-camel-case=true
# \u542F\u7528\u4E8C\u7EA7\u7F13\u5B58
mybatis.configuration.cache-enabled=true
# \u542F\u7528\u5EF6\u8FDF\u52A0\u8F7D
mybatis.configuration.lazy-loading-enabled=true
# \u4F18\u5148\u4F7F\u7528\u5217\u522B\u540D\u800C\u4E0D\u662F\u5217\u540D
mybatis.configuration.use-column-label=true
# \u8BBE\u7F6E\u9ED8\u8BA4\u83B7\u53D6\u8BB0\u5F55\u6570
mybatis.configuration.default-fetch-size=100
# \u8BBE\u7F6E\u8D85\u65F6\u65F6\u95F4
mybatis.configuration.default-statement-timeout=30

# PageHelper Configuration
pagehelper.helper-dialect=mysql
pagehelper.reasonable=true
pagehelper.support-methods-arguments=true